/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_setup_LoadInitialTargetsImages */

#ifndef _Included_com_setup_LoadInitialTargetsImages
#define _Included_com_setup_LoadInitialTargetsImages
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_setup_LoadInitialTargetsImages
 * Method:    callFeatureRecogn
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_setup_LoadInitialTargetsImages_callFeatureRecogn
  (JNIEnv *, jobject);

/*
 * Class:     com_setup_LoadInitialTargetsImages
 * Method:    analyzeFeatureRecogn
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_setup_LoadInitialTargetsImages_analyzeFeatureRecogn
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
