// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: newproto

package com.utils;

public final class Data {
	private Data() {
	}

	public static void registerAllExtensions(com.google.protobuf.ExtensionRegistry registry) {
	}

	public interface TargetImageOrBuilder extends com.google.protobuf.MessageOrBuilder {

		// repeated float keys = 1;
		/**
		 * <code>repeated float keys = 1;</code>
		 */
		java.util.List<java.lang.Float> getKeysList();

		/**
		 * <code>repeated float keys = 1;</code>
		 */
		int getKeysCount();

		/**
		 * <code>repeated float keys = 1;</code>
		 */
		float getKeys(int index);

		// repeated int32 des = 2;
		/**
		 * <code>repeated int32 des = 2;</code>
		 */
		java.util.List<java.lang.Integer> getDesList();

		/**
		 * <code>repeated int32 des = 2;</code>
		 */
		int getDesCount();

		/**
		 * <code>repeated int32 des = 2;</code>
		 */
		int getDes(int index);

		// required int32 id = 3;
		/**
		 * <code>required int32 id = 3;</code>
		 */
		boolean hasId();

		/**
		 * <code>required int32 id = 3;</code>
		 */
		int getId();

		// required int32 width = 4;
		/**
		 * <code>required int32 width = 4;</code>
		 */
		boolean hasWidth();

		/**
		 * <code>required int32 width = 4;</code>
		 */
		int getWidth();

		// required int32 height = 5;
		/**
		 * <code>required int32 height = 5;</code>
		 */
		boolean hasHeight();

		/**
		 * <code>required int32 height = 5;</code>
		 */
		int getHeight();

		// required int32 rows = 6;
		/**
		 * <code>required int32 rows = 6;</code>
		 */
		boolean hasRows();

		/**
		 * <code>required int32 rows = 6;</code>
		 */
		int getRows();

		// required int32 cols = 7;
		/**
		 * <code>required int32 cols = 7;</code>
		 */
		boolean hasCols();

		/**
		 * <code>required int32 cols = 7;</code>
		 */
		int getCols();

		// required int32 type = 8;
		/**
		 * <code>required int32 type = 8;</code>
		 */
		boolean hasType();

		/**
		 * <code>required int32 type = 8;</code>
		 */
		int getType();

		// required int32 keyNum = 9;
		/**
		 * <code>required int32 keyNum = 9;</code>
		 */
		boolean hasKeyNum();

		/**
		 * <code>required int32 keyNum = 9;</code>
		 */
		int getKeyNum();
	}

	/**
	 * Protobuf type {@code utils.TargetImage}
	 */
	public static final class TargetImage extends com.google.protobuf.GeneratedMessage implements TargetImageOrBuilder {
		// Use TargetImage.newBuilder() to construct.
		private TargetImage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
			super(builder);
			this.unknownFields = builder.getUnknownFields();
		}

		private TargetImage(boolean noInit) {
			this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance();
		}

		private static final TargetImage defaultInstance;

		public static TargetImage getDefaultInstance() {
			return defaultInstance;
		}

		public TargetImage getDefaultInstanceForType() {
			return defaultInstance;
		}

		private final com.google.protobuf.UnknownFieldSet unknownFields;

		@java.lang.Override
		public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
			return this.unknownFields;
		}

		private TargetImage(com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			initFields();
			int mutable_bitField0_ = 0;
			com.google.protobuf.UnknownFieldSet.Builder unknownFields = com.google.protobuf.UnknownFieldSet.newBuilder();
			try {
				boolean done = false;
				while (!done) {
					int tag = input.readTag();
					switch (tag) {
					case 0:
						done = true;
						break;
					default: {
						if (!parseUnknownField(input, unknownFields, extensionRegistry, tag)) {
							done = true;
						}
						break;
					}
					case 13: {
						if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
							keys_ = new java.util.ArrayList<java.lang.Float>();
							mutable_bitField0_ |= 0x00000001;
						}
						keys_.add(input.readFloat());
						break;
					}
					case 10: {
						int length = input.readRawVarint32();
						int limit = input.pushLimit(length);
						if (!((mutable_bitField0_ & 0x00000001) == 0x00000001) && input.getBytesUntilLimit() > 0) {
							keys_ = new java.util.ArrayList<java.lang.Float>();
							mutable_bitField0_ |= 0x00000001;
						}
						while (input.getBytesUntilLimit() > 0) {
							keys_.add(input.readFloat());
						}
						input.popLimit(limit);
						break;
					}
					case 16: {
						if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
							des_ = new java.util.ArrayList<java.lang.Integer>();
							mutable_bitField0_ |= 0x00000002;
						}
						des_.add(input.readInt32());
						break;
					}
					case 18: {
						int length = input.readRawVarint32();
						int limit = input.pushLimit(length);
						if (!((mutable_bitField0_ & 0x00000002) == 0x00000002) && input.getBytesUntilLimit() > 0) {
							des_ = new java.util.ArrayList<java.lang.Integer>();
							mutable_bitField0_ |= 0x00000002;
						}
						while (input.getBytesUntilLimit() > 0) {
							des_.add(input.readInt32());
						}
						input.popLimit(limit);
						break;
					}
					case 24: {
						bitField0_ |= 0x00000001;
						id_ = input.readInt32();
						break;
					}
					case 32: {
						bitField0_ |= 0x00000002;
						width_ = input.readInt32();
						break;
					}
					case 40: {
						bitField0_ |= 0x00000004;
						height_ = input.readInt32();
						break;
					}
					case 48: {
						bitField0_ |= 0x00000008;
						rows_ = input.readInt32();
						break;
					}
					case 56: {
						bitField0_ |= 0x00000010;
						cols_ = input.readInt32();
						break;
					}
					case 64: {
						bitField0_ |= 0x00000020;
						type_ = input.readInt32();
						break;
					}
					case 72: {
						bitField0_ |= 0x00000040;
						keyNum_ = input.readInt32();
						break;
					}
					}
				}
			} catch (com.google.protobuf.InvalidProtocolBufferException e) {
				throw e.setUnfinishedMessage(this);
			} catch (java.io.IOException e) {
				throw new com.google.protobuf.InvalidProtocolBufferException(e.getMessage()).setUnfinishedMessage(this);
			} finally {
				if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
					keys_ = java.util.Collections.unmodifiableList(keys_);
				}
				if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
					des_ = java.util.Collections.unmodifiableList(des_);
				}
				this.unknownFields = unknownFields.build();
				makeExtensionsImmutable();
			}
		}

		public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
			return com.utils.Data.internal_static_utils_TargetImage_descriptor;
		}

		protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
			return com.utils.Data.internal_static_utils_TargetImage_fieldAccessorTable.ensureFieldAccessorsInitialized(
					com.utils.Data.TargetImage.class, com.utils.Data.TargetImage.Builder.class);
		}

		public static com.google.protobuf.Parser<TargetImage> PARSER = new com.google.protobuf.AbstractParser<TargetImage>() {
			public TargetImage parsePartialFrom(com.google.protobuf.CodedInputStream input,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
				return new TargetImage(input, extensionRegistry);
			}
		};

		@java.lang.Override
		public com.google.protobuf.Parser<TargetImage> getParserForType() {
			return PARSER;
		}

		private int bitField0_;
		// repeated float keys = 1;
		public static final int KEYS_FIELD_NUMBER = 1;
		private java.util.List<java.lang.Float> keys_;

		/**
		 * <code>repeated float keys = 1;</code>
		 */
		public java.util.List<java.lang.Float> getKeysList() {
			return keys_;
		}

		/**
		 * <code>repeated float keys = 1;</code>
		 */
		public int getKeysCount() {
			return keys_.size();
		}

		/**
		 * <code>repeated float keys = 1;</code>
		 */
		public float getKeys(int index) {
			return keys_.get(index);
		}

		// repeated int32 des = 2;
		public static final int DES_FIELD_NUMBER = 2;
		private java.util.List<java.lang.Integer> des_;

		/**
		 * <code>repeated int32 des = 2;</code>
		 */
		public java.util.List<java.lang.Integer> getDesList() {
			return des_;
		}

		/**
		 * <code>repeated int32 des = 2;</code>
		 */
		public int getDesCount() {
			return des_.size();
		}

		/**
		 * <code>repeated int32 des = 2;</code>
		 */
		public int getDes(int index) {
			return des_.get(index);
		}

		// required int32 id = 3;
		public static final int ID_FIELD_NUMBER = 3;
		private int id_;

		/**
		 * <code>required int32 id = 3;</code>
		 */
		public boolean hasId() {
			return ((bitField0_ & 0x00000001) == 0x00000001);
		}

		/**
		 * <code>required int32 id = 3;</code>
		 */
		public int getId() {
			return id_;
		}

		// required int32 width = 4;
		public static final int WIDTH_FIELD_NUMBER = 4;
		private int width_;

		/**
		 * <code>required int32 width = 4;</code>
		 */
		public boolean hasWidth() {
			return ((bitField0_ & 0x00000002) == 0x00000002);
		}

		/**
		 * <code>required int32 width = 4;</code>
		 */
		public int getWidth() {
			return width_;
		}

		// required int32 height = 5;
		public static final int HEIGHT_FIELD_NUMBER = 5;
		private int height_;

		/**
		 * <code>required int32 height = 5;</code>
		 */
		public boolean hasHeight() {
			return ((bitField0_ & 0x00000004) == 0x00000004);
		}

		/**
		 * <code>required int32 height = 5;</code>
		 */
		public int getHeight() {
			return height_;
		}

		// required int32 rows = 6;
		public static final int ROWS_FIELD_NUMBER = 6;
		private int rows_;

		/**
		 * <code>required int32 rows = 6;</code>
		 */
		public boolean hasRows() {
			return ((bitField0_ & 0x00000008) == 0x00000008);
		}

		/**
		 * <code>required int32 rows = 6;</code>
		 */
		public int getRows() {
			return rows_;
		}

		// required int32 cols = 7;
		public static final int COLS_FIELD_NUMBER = 7;
		private int cols_;

		/**
		 * <code>required int32 cols = 7;</code>
		 */
		public boolean hasCols() {
			return ((bitField0_ & 0x00000010) == 0x00000010);
		}

		/**
		 * <code>required int32 cols = 7;</code>
		 */
		public int getCols() {
			return cols_;
		}

		// required int32 type = 8;
		public static final int TYPE_FIELD_NUMBER = 8;
		private int type_;

		/**
		 * <code>required int32 type = 8;</code>
		 */
		public boolean hasType() {
			return ((bitField0_ & 0x00000020) == 0x00000020);
		}

		/**
		 * <code>required int32 type = 8;</code>
		 */
		public int getType() {
			return type_;
		}

		// required int32 keyNum = 9;
		public static final int KEYNUM_FIELD_NUMBER = 9;
		private int keyNum_;

		/**
		 * <code>required int32 keyNum = 9;</code>
		 */
		public boolean hasKeyNum() {
			return ((bitField0_ & 0x00000040) == 0x00000040);
		}

		/**
		 * <code>required int32 keyNum = 9;</code>
		 */
		public int getKeyNum() {
			return keyNum_;
		}

		private void initFields() {
			keys_ = java.util.Collections.emptyList();
			des_ = java.util.Collections.emptyList();
			id_ = 0;
			width_ = 0;
			height_ = 0;
			rows_ = 0;
			cols_ = 0;
			type_ = 0;
			keyNum_ = 0;
		}

		private byte memoizedIsInitialized = -1;

		public final boolean isInitialized() {
			byte isInitialized = memoizedIsInitialized;
			if (isInitialized != -1)
				return isInitialized == 1;

			if (!hasId()) {
				memoizedIsInitialized = 0;
				return false;
			}
			if (!hasWidth()) {
				memoizedIsInitialized = 0;
				return false;
			}
			if (!hasHeight()) {
				memoizedIsInitialized = 0;
				return false;
			}
			if (!hasRows()) {
				memoizedIsInitialized = 0;
				return false;
			}
			if (!hasCols()) {
				memoizedIsInitialized = 0;
				return false;
			}
			if (!hasType()) {
				memoizedIsInitialized = 0;
				return false;
			}
			if (!hasKeyNum()) {
				memoizedIsInitialized = 0;
				return false;
			}
			memoizedIsInitialized = 1;
			return true;
		}

		public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
			getSerializedSize();
			for (int i = 0; i < keys_.size(); i++) {
				output.writeFloat(1, keys_.get(i));
			}
			for (int i = 0; i < des_.size(); i++) {
				output.writeInt32(2, des_.get(i));
			}
			if (((bitField0_ & 0x00000001) == 0x00000001)) {
				output.writeInt32(3, id_);
			}
			if (((bitField0_ & 0x00000002) == 0x00000002)) {
				output.writeInt32(4, width_);
			}
			if (((bitField0_ & 0x00000004) == 0x00000004)) {
				output.writeInt32(5, height_);
			}
			if (((bitField0_ & 0x00000008) == 0x00000008)) {
				output.writeInt32(6, rows_);
			}
			if (((bitField0_ & 0x00000010) == 0x00000010)) {
				output.writeInt32(7, cols_);
			}
			if (((bitField0_ & 0x00000020) == 0x00000020)) {
				output.writeInt32(8, type_);
			}
			if (((bitField0_ & 0x00000040) == 0x00000040)) {
				output.writeInt32(9, keyNum_);
			}
			getUnknownFields().writeTo(output);
		}

		private int memoizedSerializedSize = -1;

		public int getSerializedSize() {
			int size = memoizedSerializedSize;
			if (size != -1)
				return size;

			size = 0;
			{
				int dataSize = 0;
				dataSize = 4 * getKeysList().size();
				size += dataSize;
				size += 1 * getKeysList().size();
			}
			{
				int dataSize = 0;
				for (int i = 0; i < des_.size(); i++) {
					dataSize += com.google.protobuf.CodedOutputStream.computeInt32SizeNoTag(des_.get(i));
				}
				size += dataSize;
				size += 1 * getDesList().size();
			}
			if (((bitField0_ & 0x00000001) == 0x00000001)) {
				size += com.google.protobuf.CodedOutputStream.computeInt32Size(3, id_);
			}
			if (((bitField0_ & 0x00000002) == 0x00000002)) {
				size += com.google.protobuf.CodedOutputStream.computeInt32Size(4, width_);
			}
			if (((bitField0_ & 0x00000004) == 0x00000004)) {
				size += com.google.protobuf.CodedOutputStream.computeInt32Size(5, height_);
			}
			if (((bitField0_ & 0x00000008) == 0x00000008)) {
				size += com.google.protobuf.CodedOutputStream.computeInt32Size(6, rows_);
			}
			if (((bitField0_ & 0x00000010) == 0x00000010)) {
				size += com.google.protobuf.CodedOutputStream.computeInt32Size(7, cols_);
			}
			if (((bitField0_ & 0x00000020) == 0x00000020)) {
				size += com.google.protobuf.CodedOutputStream.computeInt32Size(8, type_);
			}
			if (((bitField0_ & 0x00000040) == 0x00000040)) {
				size += com.google.protobuf.CodedOutputStream.computeInt32Size(9, keyNum_);
			}
			size += getUnknownFields().getSerializedSize();
			memoizedSerializedSize = size;
			return size;
		}

		private static final long serialVersionUID = 0L;

		@java.lang.Override
		protected java.lang.Object writeReplace() throws java.io.ObjectStreamException {
			return super.writeReplace();
		}

		public static com.utils.Data.TargetImage parseFrom(com.google.protobuf.ByteString data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data);
		}

		public static com.utils.Data.TargetImage parseFrom(com.google.protobuf.ByteString data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data, extensionRegistry);
		}

		public static com.utils.Data.TargetImage parseFrom(byte[] data) throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data);
		}

		public static com.utils.Data.TargetImage parseFrom(byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data, extensionRegistry);
		}

		public static com.utils.Data.TargetImage parseFrom(java.io.InputStream input) throws java.io.IOException {
			return PARSER.parseFrom(input);
		}

		public static com.utils.Data.TargetImage parseFrom(java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return PARSER.parseFrom(input, extensionRegistry);
		}

		public static com.utils.Data.TargetImage parseDelimitedFrom(java.io.InputStream input) throws java.io.IOException {
			return PARSER.parseDelimitedFrom(input);
		}

		public static com.utils.Data.TargetImage parseDelimitedFrom(java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
			return PARSER.parseDelimitedFrom(input, extensionRegistry);
		}

		public static com.utils.Data.TargetImage parseFrom(com.google.protobuf.CodedInputStream input) throws java.io.IOException {
			return PARSER.parseFrom(input);
		}

		public static com.utils.Data.TargetImage parseFrom(com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
			return PARSER.parseFrom(input, extensionRegistry);
		}

		public static Builder newBuilder() {
			return Builder.create();
		}

		public Builder newBuilderForType() {
			return newBuilder();
		}

		public static Builder newBuilder(com.utils.Data.TargetImage prototype) {
			return newBuilder().mergeFrom(prototype);
		}

		public Builder toBuilder() {
			return newBuilder(this);
		}

		@java.lang.Override
		protected Builder newBuilderForType(com.google.protobuf.GeneratedMessage.BuilderParent parent) {
			Builder builder = new Builder(parent);
			return builder;
		}

		/**
		 * Protobuf type {@code utils.TargetImage}
		 */
		public static final class Builder extends com.google.protobuf.GeneratedMessage.Builder<Builder> implements
				com.utils.Data.TargetImageOrBuilder {
			public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
				return com.utils.Data.internal_static_utils_TargetImage_descriptor;
			}

			protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
				return com.utils.Data.internal_static_utils_TargetImage_fieldAccessorTable.ensureFieldAccessorsInitialized(
						com.utils.Data.TargetImage.class, com.utils.Data.TargetImage.Builder.class);
			}

			// Construct using com.utils.Data.TargetImage.newBuilder()
			private Builder() {
				maybeForceBuilderInitialization();
			}

			private Builder(com.google.protobuf.GeneratedMessage.BuilderParent parent) {
				super(parent);
				maybeForceBuilderInitialization();
			}

			private void maybeForceBuilderInitialization() {
				if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
				}
			}

			private static Builder create() {
				return new Builder();
			}

			public Builder clear() {
				super.clear();
				keys_ = java.util.Collections.emptyList();
				bitField0_ = (bitField0_ & ~0x00000001);
				des_ = java.util.Collections.emptyList();
				bitField0_ = (bitField0_ & ~0x00000002);
				id_ = 0;
				bitField0_ = (bitField0_ & ~0x00000004);
				width_ = 0;
				bitField0_ = (bitField0_ & ~0x00000008);
				height_ = 0;
				bitField0_ = (bitField0_ & ~0x00000010);
				rows_ = 0;
				bitField0_ = (bitField0_ & ~0x00000020);
				cols_ = 0;
				bitField0_ = (bitField0_ & ~0x00000040);
				type_ = 0;
				bitField0_ = (bitField0_ & ~0x00000080);
				keyNum_ = 0;
				bitField0_ = (bitField0_ & ~0x00000100);
				return this;
			}

			public Builder clone() {
				return create().mergeFrom(buildPartial());
			}

			public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
				return com.utils.Data.internal_static_utils_TargetImage_descriptor;
			}

			public com.utils.Data.TargetImage getDefaultInstanceForType() {
				return com.utils.Data.TargetImage.getDefaultInstance();
			}

			public com.utils.Data.TargetImage build() {
				com.utils.Data.TargetImage result = buildPartial();
				if (!result.isInitialized()) {
					throw newUninitializedMessageException(result);
				}
				return result;
			}

			public com.utils.Data.TargetImage buildPartial() {
				com.utils.Data.TargetImage result = new com.utils.Data.TargetImage(this);
				int from_bitField0_ = bitField0_;
				int to_bitField0_ = 0;
				if (((bitField0_ & 0x00000001) == 0x00000001)) {
					keys_ = java.util.Collections.unmodifiableList(keys_);
					bitField0_ = (bitField0_ & ~0x00000001);
				}
				result.keys_ = keys_;
				if (((bitField0_ & 0x00000002) == 0x00000002)) {
					des_ = java.util.Collections.unmodifiableList(des_);
					bitField0_ = (bitField0_ & ~0x00000002);
				}
				result.des_ = des_;
				if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
					to_bitField0_ |= 0x00000001;
				}
				result.id_ = id_;
				if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
					to_bitField0_ |= 0x00000002;
				}
				result.width_ = width_;
				if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
					to_bitField0_ |= 0x00000004;
				}
				result.height_ = height_;
				if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
					to_bitField0_ |= 0x00000008;
				}
				result.rows_ = rows_;
				if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
					to_bitField0_ |= 0x00000010;
				}
				result.cols_ = cols_;
				if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
					to_bitField0_ |= 0x00000020;
				}
				result.type_ = type_;
				if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
					to_bitField0_ |= 0x00000040;
				}
				result.keyNum_ = keyNum_;
				result.bitField0_ = to_bitField0_;
				onBuilt();
				return result;
			}

			public Builder mergeFrom(com.google.protobuf.Message other) {
				if (other instanceof com.utils.Data.TargetImage) {
					return mergeFrom((com.utils.Data.TargetImage) other);
				} else {
					super.mergeFrom(other);
					return this;
				}
			}

			public Builder mergeFrom(com.utils.Data.TargetImage other) {
				if (other == com.utils.Data.TargetImage.getDefaultInstance())
					return this;
				if (!other.keys_.isEmpty()) {
					if (keys_.isEmpty()) {
						keys_ = other.keys_;
						bitField0_ = (bitField0_ & ~0x00000001);
					} else {
						ensureKeysIsMutable();
						keys_.addAll(other.keys_);
					}
					onChanged();
				}
				if (!other.des_.isEmpty()) {
					if (des_.isEmpty()) {
						des_ = other.des_;
						bitField0_ = (bitField0_ & ~0x00000002);
					} else {
						ensureDesIsMutable();
						des_.addAll(other.des_);
					}
					onChanged();
				}
				if (other.hasId()) {
					setId(other.getId());
				}
				if (other.hasWidth()) {
					setWidth(other.getWidth());
				}
				if (other.hasHeight()) {
					setHeight(other.getHeight());
				}
				if (other.hasRows()) {
					setRows(other.getRows());
				}
				if (other.hasCols()) {
					setCols(other.getCols());
				}
				if (other.hasType()) {
					setType(other.getType());
				}
				if (other.hasKeyNum()) {
					setKeyNum(other.getKeyNum());
				}
				this.mergeUnknownFields(other.getUnknownFields());
				return this;
			}

			public final boolean isInitialized() {
				if (!hasId()) {

					return false;
				}
				if (!hasWidth()) {

					return false;
				}
				if (!hasHeight()) {

					return false;
				}
				if (!hasRows()) {

					return false;
				}
				if (!hasCols()) {

					return false;
				}
				if (!hasType()) {

					return false;
				}
				if (!hasKeyNum()) {

					return false;
				}
				return true;
			}

			public Builder mergeFrom(com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
					throws java.io.IOException {
				com.utils.Data.TargetImage parsedMessage = null;
				try {
					parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
				} catch (com.google.protobuf.InvalidProtocolBufferException e) {
					parsedMessage = (com.utils.Data.TargetImage) e.getUnfinishedMessage();
					throw e;
				} finally {
					if (parsedMessage != null) {
						mergeFrom(parsedMessage);
					}
				}
				return this;
			}

			private int bitField0_;

			// repeated float keys = 1;
			private java.util.List<java.lang.Float> keys_ = java.util.Collections.emptyList();

			private void ensureKeysIsMutable() {
				if (!((bitField0_ & 0x00000001) == 0x00000001)) {
					keys_ = new java.util.ArrayList<java.lang.Float>(keys_);
					bitField0_ |= 0x00000001;
				}
			}

			/**
			 * <code>repeated float keys = 1;</code>
			 */
			public java.util.List<java.lang.Float> getKeysList() {
				return java.util.Collections.unmodifiableList(keys_);
			}

			/**
			 * <code>repeated float keys = 1;</code>
			 */
			public int getKeysCount() {
				return keys_.size();
			}

			/**
			 * <code>repeated float keys = 1;</code>
			 */
			public float getKeys(int index) {
				return keys_.get(index);
			}

			/**
			 * <code>repeated float keys = 1;</code>
			 */
			public Builder setKeys(int index, float value) {
				ensureKeysIsMutable();
				keys_.set(index, value);
				onChanged();
				return this;
			}

			/**
			 * <code>repeated float keys = 1;</code>
			 */
			public Builder addKeys(float value) {
				ensureKeysIsMutable();
				keys_.add(value);
				onChanged();
				return this;
			}

			/**
			 * <code>repeated float keys = 1;</code>
			 */
			public Builder addAllKeys(java.lang.Iterable<? extends java.lang.Float> values) {
				ensureKeysIsMutable();
				super.addAll(values, keys_);
				onChanged();
				return this;
			}

			/**
			 * <code>repeated float keys = 1;</code>
			 */
			public Builder clearKeys() {
				keys_ = java.util.Collections.emptyList();
				bitField0_ = (bitField0_ & ~0x00000001);
				onChanged();
				return this;
			}

			// repeated int32 des = 2;
			private java.util.List<java.lang.Integer> des_ = java.util.Collections.emptyList();

			private void ensureDesIsMutable() {
				if (!((bitField0_ & 0x00000002) == 0x00000002)) {
					des_ = new java.util.ArrayList<java.lang.Integer>(des_);
					bitField0_ |= 0x00000002;
				}
			}

			/**
			 * <code>repeated int32 des = 2;</code>
			 */
			public java.util.List<java.lang.Integer> getDesList() {
				return java.util.Collections.unmodifiableList(des_);
			}

			/**
			 * <code>repeated int32 des = 2;</code>
			 */
			public int getDesCount() {
				return des_.size();
			}

			/**
			 * <code>repeated int32 des = 2;</code>
			 */
			public int getDes(int index) {
				return des_.get(index);
			}

			/**
			 * <code>repeated int32 des = 2;</code>
			 */
			public Builder setDes(int index, int value) {
				ensureDesIsMutable();
				des_.set(index, value);
				onChanged();
				return this;
			}

			/**
			 * <code>repeated int32 des = 2;</code>
			 */
			public Builder addDes(int value) {
				ensureDesIsMutable();
				des_.add(value);
				onChanged();
				return this;
			}

			/**
			 * <code>repeated int32 des = 2;</code>
			 */
			public Builder addAllDes(java.lang.Iterable<? extends java.lang.Integer> values) {
				ensureDesIsMutable();
				super.addAll(values, des_);
				onChanged();
				return this;
			}

			/**
			 * <code>repeated int32 des = 2;</code>
			 */
			public Builder clearDes() {
				des_ = java.util.Collections.emptyList();
				bitField0_ = (bitField0_ & ~0x00000002);
				onChanged();
				return this;
			}

			// required int32 id = 3;
			private int id_;

			/**
			 * <code>required int32 id = 3;</code>
			 */
			public boolean hasId() {
				return ((bitField0_ & 0x00000004) == 0x00000004);
			}

			/**
			 * <code>required int32 id = 3;</code>
			 */
			public int getId() {
				return id_;
			}

			/**
			 * <code>required int32 id = 3;</code>
			 */
			public Builder setId(int value) {
				bitField0_ |= 0x00000004;
				id_ = value;
				onChanged();
				return this;
			}

			/**
			 * <code>required int32 id = 3;</code>
			 */
			public Builder clearId() {
				bitField0_ = (bitField0_ & ~0x00000004);
				id_ = 0;
				onChanged();
				return this;
			}

			// required int32 width = 4;
			private int width_;

			/**
			 * <code>required int32 width = 4;</code>
			 */
			public boolean hasWidth() {
				return ((bitField0_ & 0x00000008) == 0x00000008);
			}

			/**
			 * <code>required int32 width = 4;</code>
			 */
			public int getWidth() {
				return width_;
			}

			/**
			 * <code>required int32 width = 4;</code>
			 */
			public Builder setWidth(int value) {
				bitField0_ |= 0x00000008;
				width_ = value;
				onChanged();
				return this;
			}

			/**
			 * <code>required int32 width = 4;</code>
			 */
			public Builder clearWidth() {
				bitField0_ = (bitField0_ & ~0x00000008);
				width_ = 0;
				onChanged();
				return this;
			}

			// required int32 height = 5;
			private int height_;

			/**
			 * <code>required int32 height = 5;</code>
			 */
			public boolean hasHeight() {
				return ((bitField0_ & 0x00000010) == 0x00000010);
			}

			/**
			 * <code>required int32 height = 5;</code>
			 */
			public int getHeight() {
				return height_;
			}

			/**
			 * <code>required int32 height = 5;</code>
			 */
			public Builder setHeight(int value) {
				bitField0_ |= 0x00000010;
				height_ = value;
				onChanged();
				return this;
			}

			/**
			 * <code>required int32 height = 5;</code>
			 */
			public Builder clearHeight() {
				bitField0_ = (bitField0_ & ~0x00000010);
				height_ = 0;
				onChanged();
				return this;
			}

			// required int32 rows = 6;
			private int rows_;

			/**
			 * <code>required int32 rows = 6;</code>
			 */
			public boolean hasRows() {
				return ((bitField0_ & 0x00000020) == 0x00000020);
			}

			/**
			 * <code>required int32 rows = 6;</code>
			 */
			public int getRows() {
				return rows_;
			}

			/**
			 * <code>required int32 rows = 6;</code>
			 */
			public Builder setRows(int value) {
				bitField0_ |= 0x00000020;
				rows_ = value;
				onChanged();
				return this;
			}

			/**
			 * <code>required int32 rows = 6;</code>
			 */
			public Builder clearRows() {
				bitField0_ = (bitField0_ & ~0x00000020);
				rows_ = 0;
				onChanged();
				return this;
			}

			// required int32 cols = 7;
			private int cols_;

			/**
			 * <code>required int32 cols = 7;</code>
			 */
			public boolean hasCols() {
				return ((bitField0_ & 0x00000040) == 0x00000040);
			}

			/**
			 * <code>required int32 cols = 7;</code>
			 */
			public int getCols() {
				return cols_;
			}

			/**
			 * <code>required int32 cols = 7;</code>
			 */
			public Builder setCols(int value) {
				bitField0_ |= 0x00000040;
				cols_ = value;
				onChanged();
				return this;
			}

			/**
			 * <code>required int32 cols = 7;</code>
			 */
			public Builder clearCols() {
				bitField0_ = (bitField0_ & ~0x00000040);
				cols_ = 0;
				onChanged();
				return this;
			}

			// required int32 type = 8;
			private int type_;

			/**
			 * <code>required int32 type = 8;</code>
			 */
			public boolean hasType() {
				return ((bitField0_ & 0x00000080) == 0x00000080);
			}

			/**
			 * <code>required int32 type = 8;</code>
			 */
			public int getType() {
				return type_;
			}

			/**
			 * <code>required int32 type = 8;</code>
			 */
			public Builder setType(int value) {
				bitField0_ |= 0x00000080;
				type_ = value;
				onChanged();
				return this;
			}

			/**
			 * <code>required int32 type = 8;</code>
			 */
			public Builder clearType() {
				bitField0_ = (bitField0_ & ~0x00000080);
				type_ = 0;
				onChanged();
				return this;
			}

			// required int32 keyNum = 9;
			private int keyNum_;

			/**
			 * <code>required int32 keyNum = 9;</code>
			 */
			public boolean hasKeyNum() {
				return ((bitField0_ & 0x00000100) == 0x00000100);
			}

			/**
			 * <code>required int32 keyNum = 9;</code>
			 */
			public int getKeyNum() {
				return keyNum_;
			}

			/**
			 * <code>required int32 keyNum = 9;</code>
			 */
			public Builder setKeyNum(int value) {
				bitField0_ |= 0x00000100;
				keyNum_ = value;
				onChanged();
				return this;
			}

			/**
			 * <code>required int32 keyNum = 9;</code>
			 */
			public Builder clearKeyNum() {
				bitField0_ = (bitField0_ & ~0x00000100);
				keyNum_ = 0;
				onChanged();
				return this;
			}

			// @@protoc_insertion_point(builder_scope:utils.TargetImage)
		}

		static {
			defaultInstance = new TargetImage(true);
			defaultInstance.initFields();
		}

		// @@protoc_insertion_point(class_scope:utils.TargetImage)
	}

	public interface VectorTargetImagesOrBuilder extends com.google.protobuf.MessageOrBuilder {

		// repeated .utils.TargetImage targets = 1;
		/**
		 * <code>repeated .utils.TargetImage targets = 1;</code>
		 */
		java.util.List<com.utils.Data.TargetImage> getTargetsList();

		/**
		 * <code>repeated .utils.TargetImage targets = 1;</code>
		 */
		com.utils.Data.TargetImage getTargets(int index);

		/**
		 * <code>repeated .utils.TargetImage targets = 1;</code>
		 */
		int getTargetsCount();

		/**
		 * <code>repeated .utils.TargetImage targets = 1;</code>
		 */
		java.util.List<? extends com.utils.Data.TargetImageOrBuilder> getTargetsOrBuilderList();

		/**
		 * <code>repeated .utils.TargetImage targets = 1;</code>
		 */
		com.utils.Data.TargetImageOrBuilder getTargetsOrBuilder(int index);

		// required int32 dataSize = 2;
		/**
		 * <code>required int32 dataSize = 2;</code>
		 */
		boolean hasDataSize();

		/**
		 * <code>required int32 dataSize = 2;</code>
		 */
		int getDataSize();

		// required int32 size = 3;
		/**
		 * <code>required int32 size = 3;</code>
		 */
		boolean hasSize();

		/**
		 * <code>required int32 size = 3;</code>
		 */
		int getSize();
	}

	/**
	 * Protobuf type {@code utils.VectorTargetImages}
	 */
	public static final class VectorTargetImages extends com.google.protobuf.GeneratedMessage implements VectorTargetImagesOrBuilder {
		// Use VectorTargetImages.newBuilder() to construct.
		private VectorTargetImages(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
			super(builder);
			this.unknownFields = builder.getUnknownFields();
		}

		private VectorTargetImages(boolean noInit) {
			this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance();
		}

		private static final VectorTargetImages defaultInstance;

		public static VectorTargetImages getDefaultInstance() {
			return defaultInstance;
		}

		public VectorTargetImages getDefaultInstanceForType() {
			return defaultInstance;
		}

		private final com.google.protobuf.UnknownFieldSet unknownFields;

		@java.lang.Override
		public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
			return this.unknownFields;
		}

		private VectorTargetImages(com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			initFields();
			int mutable_bitField0_ = 0;
			com.google.protobuf.UnknownFieldSet.Builder unknownFields = com.google.protobuf.UnknownFieldSet.newBuilder();
			try {
				boolean done = false;
				while (!done) {
					int tag = input.readTag();
					switch (tag) {
					case 0:
						done = true;
						break;
					default: {
						if (!parseUnknownField(input, unknownFields, extensionRegistry, tag)) {
							done = true;
						}
						break;
					}
					case 10: {
						if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
							targets_ = new java.util.ArrayList<com.utils.Data.TargetImage>();
							mutable_bitField0_ |= 0x00000001;
						}
						targets_.add(input.readMessage(com.utils.Data.TargetImage.PARSER, extensionRegistry));
						break;
					}
					case 16: {
						bitField0_ |= 0x00000001;
						dataSize_ = input.readInt32();
						break;
					}
					case 24: {
						bitField0_ |= 0x00000002;
						size_ = input.readInt32();
						break;
					}
					}
				}
			} catch (com.google.protobuf.InvalidProtocolBufferException e) {
				throw e.setUnfinishedMessage(this);
			} catch (java.io.IOException e) {
				throw new com.google.protobuf.InvalidProtocolBufferException(e.getMessage()).setUnfinishedMessage(this);
			} finally {
				if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
					targets_ = java.util.Collections.unmodifiableList(targets_);
				}
				this.unknownFields = unknownFields.build();
				makeExtensionsImmutable();
			}
		}

		public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
			return com.utils.Data.internal_static_utils_VectorTargetImages_descriptor;
		}

		protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
			return com.utils.Data.internal_static_utils_VectorTargetImages_fieldAccessorTable.ensureFieldAccessorsInitialized(
					com.utils.Data.VectorTargetImages.class, com.utils.Data.VectorTargetImages.Builder.class);
		}

		public static com.google.protobuf.Parser<VectorTargetImages> PARSER = new com.google.protobuf.AbstractParser<VectorTargetImages>() {
			public VectorTargetImages parsePartialFrom(com.google.protobuf.CodedInputStream input,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
				return new VectorTargetImages(input, extensionRegistry);
			}
		};

		@java.lang.Override
		public com.google.protobuf.Parser<VectorTargetImages> getParserForType() {
			return PARSER;
		}

		private int bitField0_;
		// repeated .utils.TargetImage targets = 1;
		public static final int TARGETS_FIELD_NUMBER = 1;
		private java.util.List<com.utils.Data.TargetImage> targets_;

		/**
		 * <code>repeated .utils.TargetImage targets = 1;</code>
		 */
		public java.util.List<com.utils.Data.TargetImage> getTargetsList() {
			return targets_;
		}

		/**
		 * <code>repeated .utils.TargetImage targets = 1;</code>
		 */
		public java.util.List<? extends com.utils.Data.TargetImageOrBuilder> getTargetsOrBuilderList() {
			return targets_;
		}

		/**
		 * <code>repeated .utils.TargetImage targets = 1;</code>
		 */
		public int getTargetsCount() {
			return targets_.size();
		}

		/**
		 * <code>repeated .utils.TargetImage targets = 1;</code>
		 */
		public com.utils.Data.TargetImage getTargets(int index) {
			return targets_.get(index);
		}

		/**
		 * <code>repeated .utils.TargetImage targets = 1;</code>
		 */
		public com.utils.Data.TargetImageOrBuilder getTargetsOrBuilder(int index) {
			return targets_.get(index);
		}

		// required int32 dataSize = 2;
		public static final int DATASIZE_FIELD_NUMBER = 2;
		private int dataSize_;

		/**
		 * <code>required int32 dataSize = 2;</code>
		 */
		public boolean hasDataSize() {
			return ((bitField0_ & 0x00000001) == 0x00000001);
		}

		/**
		 * <code>required int32 dataSize = 2;</code>
		 */
		public int getDataSize() {
			return dataSize_;
		}

		// required int32 size = 3;
		public static final int SIZE_FIELD_NUMBER = 3;
		private int size_;

		/**
		 * <code>required int32 size = 3;</code>
		 */
		public boolean hasSize() {
			return ((bitField0_ & 0x00000002) == 0x00000002);
		}

		/**
		 * <code>required int32 size = 3;</code>
		 */
		public int getSize() {
			return size_;
		}

		private void initFields() {
			targets_ = java.util.Collections.emptyList();
			dataSize_ = 0;
			size_ = 0;
		}

		private byte memoizedIsInitialized = -1;

		public final boolean isInitialized() {
			byte isInitialized = memoizedIsInitialized;
			if (isInitialized != -1)
				return isInitialized == 1;

			if (!hasDataSize()) {
				memoizedIsInitialized = 0;
				return false;
			}
			if (!hasSize()) {
				memoizedIsInitialized = 0;
				return false;
			}
			for (int i = 0; i < getTargetsCount(); i++) {
				if (!getTargets(i).isInitialized()) {
					memoizedIsInitialized = 0;
					return false;
				}
			}
			memoizedIsInitialized = 1;
			return true;
		}

		public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
			getSerializedSize();
			for (int i = 0; i < targets_.size(); i++) {
				output.writeMessage(1, targets_.get(i));
			}
			if (((bitField0_ & 0x00000001) == 0x00000001)) {
				output.writeInt32(2, dataSize_);
			}
			if (((bitField0_ & 0x00000002) == 0x00000002)) {
				output.writeInt32(3, size_);
			}
			getUnknownFields().writeTo(output);
		}

		private int memoizedSerializedSize = -1;

		public int getSerializedSize() {
			int size = memoizedSerializedSize;
			if (size != -1)
				return size;

			size = 0;
			for (int i = 0; i < targets_.size(); i++) {
				size += com.google.protobuf.CodedOutputStream.computeMessageSize(1, targets_.get(i));
			}
			if (((bitField0_ & 0x00000001) == 0x00000001)) {
				size += com.google.protobuf.CodedOutputStream.computeInt32Size(2, dataSize_);
			}
			if (((bitField0_ & 0x00000002) == 0x00000002)) {
				size += com.google.protobuf.CodedOutputStream.computeInt32Size(3, size_);
			}
			size += getUnknownFields().getSerializedSize();
			memoizedSerializedSize = size;
			return size;
		}

		private static final long serialVersionUID = 0L;

		@java.lang.Override
		protected java.lang.Object writeReplace() throws java.io.ObjectStreamException {
			return super.writeReplace();
		}

		public static com.utils.Data.VectorTargetImages parseFrom(com.google.protobuf.ByteString data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data);
		}

		public static com.utils.Data.VectorTargetImages parseFrom(com.google.protobuf.ByteString data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data, extensionRegistry);
		}

		public static com.utils.Data.VectorTargetImages parseFrom(byte[] data) throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data);
		}

		public static com.utils.Data.VectorTargetImages parseFrom(byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data, extensionRegistry);
		}

		public static com.utils.Data.VectorTargetImages parseFrom(java.io.InputStream input) throws java.io.IOException {
			return PARSER.parseFrom(input);
		}

		public static com.utils.Data.VectorTargetImages parseFrom(java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
			return PARSER.parseFrom(input, extensionRegistry);
		}

		public static com.utils.Data.VectorTargetImages parseDelimitedFrom(java.io.InputStream input) throws java.io.IOException {
			return PARSER.parseDelimitedFrom(input);
		}

		public static com.utils.Data.VectorTargetImages parseDelimitedFrom(java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
			return PARSER.parseDelimitedFrom(input, extensionRegistry);
		}

		public static com.utils.Data.VectorTargetImages parseFrom(com.google.protobuf.CodedInputStream input) throws java.io.IOException {
			return PARSER.parseFrom(input);
		}

		public static com.utils.Data.VectorTargetImages parseFrom(com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
			return PARSER.parseFrom(input, extensionRegistry);
		}

		public static Builder newBuilder() {
			return Builder.create();
		}

		public Builder newBuilderForType() {
			return newBuilder();
		}

		public static Builder newBuilder(com.utils.Data.VectorTargetImages prototype) {
			return newBuilder().mergeFrom(prototype);
		}

		public Builder toBuilder() {
			return newBuilder(this);
		}

		@java.lang.Override
		protected Builder newBuilderForType(com.google.protobuf.GeneratedMessage.BuilderParent parent) {
			Builder builder = new Builder(parent);
			return builder;
		}

		/**
		 * Protobuf type {@code utils.VectorTargetImages}
		 */
		public static final class Builder extends com.google.protobuf.GeneratedMessage.Builder<Builder> implements
				com.utils.Data.VectorTargetImagesOrBuilder {
			public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
				return com.utils.Data.internal_static_utils_VectorTargetImages_descriptor;
			}

			protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
				return com.utils.Data.internal_static_utils_VectorTargetImages_fieldAccessorTable.ensureFieldAccessorsInitialized(
						com.utils.Data.VectorTargetImages.class, com.utils.Data.VectorTargetImages.Builder.class);
			}

			// Construct using com.utils.Data.VectorTargetImages.newBuilder()
			private Builder() {
				maybeForceBuilderInitialization();
			}

			private Builder(com.google.protobuf.GeneratedMessage.BuilderParent parent) {
				super(parent);
				maybeForceBuilderInitialization();
			}

			private void maybeForceBuilderInitialization() {
				if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
					getTargetsFieldBuilder();
				}
			}

			private static Builder create() {
				return new Builder();
			}

			public Builder clear() {
				super.clear();
				if (targetsBuilder_ == null) {
					targets_ = java.util.Collections.emptyList();
					bitField0_ = (bitField0_ & ~0x00000001);
				} else {
					targetsBuilder_.clear();
				}
				dataSize_ = 0;
				bitField0_ = (bitField0_ & ~0x00000002);
				size_ = 0;
				bitField0_ = (bitField0_ & ~0x00000004);
				return this;
			}

			public Builder clone() {
				return create().mergeFrom(buildPartial());
			}

			public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
				return com.utils.Data.internal_static_utils_VectorTargetImages_descriptor;
			}

			public com.utils.Data.VectorTargetImages getDefaultInstanceForType() {
				return com.utils.Data.VectorTargetImages.getDefaultInstance();
			}

			public com.utils.Data.VectorTargetImages build() {
				com.utils.Data.VectorTargetImages result = buildPartial();
				if (!result.isInitialized()) {
					throw newUninitializedMessageException(result);
				}
				return result;
			}

			public com.utils.Data.VectorTargetImages buildPartial() {
				com.utils.Data.VectorTargetImages result = new com.utils.Data.VectorTargetImages(this);
				int from_bitField0_ = bitField0_;
				int to_bitField0_ = 0;
				if (targetsBuilder_ == null) {
					if (((bitField0_ & 0x00000001) == 0x00000001)) {
						targets_ = java.util.Collections.unmodifiableList(targets_);
						bitField0_ = (bitField0_ & ~0x00000001);
					}
					result.targets_ = targets_;
				} else {
					result.targets_ = targetsBuilder_.build();
				}
				if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
					to_bitField0_ |= 0x00000001;
				}
				result.dataSize_ = dataSize_;
				if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
					to_bitField0_ |= 0x00000002;
				}
				result.size_ = size_;
				result.bitField0_ = to_bitField0_;
				onBuilt();
				return result;
			}

			public Builder mergeFrom(com.google.protobuf.Message other) {
				if (other instanceof com.utils.Data.VectorTargetImages) {
					return mergeFrom((com.utils.Data.VectorTargetImages) other);
				} else {
					super.mergeFrom(other);
					return this;
				}
			}

			public Builder mergeFrom(com.utils.Data.VectorTargetImages other) {
				if (other == com.utils.Data.VectorTargetImages.getDefaultInstance())
					return this;
				if (targetsBuilder_ == null) {
					if (!other.targets_.isEmpty()) {
						if (targets_.isEmpty()) {
							targets_ = other.targets_;
							bitField0_ = (bitField0_ & ~0x00000001);
						} else {
							ensureTargetsIsMutable();
							targets_.addAll(other.targets_);
						}
						onChanged();
					}
				} else {
					if (!other.targets_.isEmpty()) {
						if (targetsBuilder_.isEmpty()) {
							targetsBuilder_.dispose();
							targetsBuilder_ = null;
							targets_ = other.targets_;
							bitField0_ = (bitField0_ & ~0x00000001);
							targetsBuilder_ = com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ? getTargetsFieldBuilder() : null;
						} else {
							targetsBuilder_.addAllMessages(other.targets_);
						}
					}
				}
				if (other.hasDataSize()) {
					setDataSize(other.getDataSize());
				}
				if (other.hasSize()) {
					setSize(other.getSize());
				}
				this.mergeUnknownFields(other.getUnknownFields());
				return this;
			}

			public final boolean isInitialized() {
				if (!hasDataSize()) {

					return false;
				}
				if (!hasSize()) {

					return false;
				}
				for (int i = 0; i < getTargetsCount(); i++) {
					if (!getTargets(i).isInitialized()) {

						return false;
					}
				}
				return true;
			}

			public Builder mergeFrom(com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
					throws java.io.IOException {
				com.utils.Data.VectorTargetImages parsedMessage = null;
				try {
					parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
				} catch (com.google.protobuf.InvalidProtocolBufferException e) {
					parsedMessage = (com.utils.Data.VectorTargetImages) e.getUnfinishedMessage();
					throw e;
				} finally {
					if (parsedMessage != null) {
						mergeFrom(parsedMessage);
					}
				}
				return this;
			}

			private int bitField0_;

			// repeated .utils.TargetImage targets = 1;
			private java.util.List<com.utils.Data.TargetImage> targets_ = java.util.Collections.emptyList();

			private void ensureTargetsIsMutable() {
				if (!((bitField0_ & 0x00000001) == 0x00000001)) {
					targets_ = new java.util.ArrayList<com.utils.Data.TargetImage>(targets_);
					bitField0_ |= 0x00000001;
				}
			}

			private com.google.protobuf.RepeatedFieldBuilder<com.utils.Data.TargetImage, com.utils.Data.TargetImage.Builder, com.utils.Data.TargetImageOrBuilder> targetsBuilder_;

			/**
			 * <code>repeated .utils.TargetImage targets = 1;</code>
			 */
			public java.util.List<com.utils.Data.TargetImage> getTargetsList() {
				if (targetsBuilder_ == null) {
					return java.util.Collections.unmodifiableList(targets_);
				} else {
					return targetsBuilder_.getMessageList();
				}
			}

			/**
			 * <code>repeated .utils.TargetImage targets = 1;</code>
			 */
			public int getTargetsCount() {
				if (targetsBuilder_ == null) {
					return targets_.size();
				} else {
					return targetsBuilder_.getCount();
				}
			}

			/**
			 * <code>repeated .utils.TargetImage targets = 1;</code>
			 */
			public com.utils.Data.TargetImage getTargets(int index) {
				if (targetsBuilder_ == null) {
					return targets_.get(index);
				} else {
					return targetsBuilder_.getMessage(index);
				}
			}

			/**
			 * <code>repeated .utils.TargetImage targets = 1;</code>
			 */
			public Builder setTargets(int index, com.utils.Data.TargetImage value) {
				if (targetsBuilder_ == null) {
					if (value == null) {
						throw new NullPointerException();
					}
					ensureTargetsIsMutable();
					targets_.set(index, value);
					onChanged();
				} else {
					targetsBuilder_.setMessage(index, value);
				}
				return this;
			}

			/**
			 * <code>repeated .utils.TargetImage targets = 1;</code>
			 */
			public Builder setTargets(int index, com.utils.Data.TargetImage.Builder builderForValue) {
				if (targetsBuilder_ == null) {
					ensureTargetsIsMutable();
					targets_.set(index, builderForValue.build());
					onChanged();
				} else {
					targetsBuilder_.setMessage(index, builderForValue.build());
				}
				return this;
			}

			/**
			 * <code>repeated .utils.TargetImage targets = 1;</code>
			 */
			public Builder addTargets(com.utils.Data.TargetImage value) {
				if (targetsBuilder_ == null) {
					if (value == null) {
						throw new NullPointerException();
					}
					ensureTargetsIsMutable();
					targets_.add(value);
					onChanged();
				} else {
					targetsBuilder_.addMessage(value);
				}
				return this;
			}

			/**
			 * <code>repeated .utils.TargetImage targets = 1;</code>
			 */
			public Builder addTargets(int index, com.utils.Data.TargetImage value) {
				if (targetsBuilder_ == null) {
					if (value == null) {
						throw new NullPointerException();
					}
					ensureTargetsIsMutable();
					targets_.add(index, value);
					onChanged();
				} else {
					targetsBuilder_.addMessage(index, value);
				}
				return this;
			}

			/**
			 * <code>repeated .utils.TargetImage targets = 1;</code>
			 */
			public Builder addTargets(com.utils.Data.TargetImage.Builder builderForValue) {
				if (targetsBuilder_ == null) {
					ensureTargetsIsMutable();
					targets_.add(builderForValue.build());
					onChanged();
				} else {
					targetsBuilder_.addMessage(builderForValue.build());
				}
				return this;
			}

			/**
			 * <code>repeated .utils.TargetImage targets = 1;</code>
			 */
			public Builder addTargets(int index, com.utils.Data.TargetImage.Builder builderForValue) {
				if (targetsBuilder_ == null) {
					ensureTargetsIsMutable();
					targets_.add(index, builderForValue.build());
					onChanged();
				} else {
					targetsBuilder_.addMessage(index, builderForValue.build());
				}
				return this;
			}

			/**
			 * <code>repeated .utils.TargetImage targets = 1;</code>
			 */
			public Builder addAllTargets(java.lang.Iterable<? extends com.utils.Data.TargetImage> values) {
				if (targetsBuilder_ == null) {
					ensureTargetsIsMutable();
					super.addAll(values, targets_);
					onChanged();
				} else {
					targetsBuilder_.addAllMessages(values);
				}
				return this;
			}

			/**
			 * <code>repeated .utils.TargetImage targets = 1;</code>
			 */
			public Builder clearTargets() {
				if (targetsBuilder_ == null) {
					targets_ = java.util.Collections.emptyList();
					bitField0_ = (bitField0_ & ~0x00000001);
					onChanged();
				} else {
					targetsBuilder_.clear();
				}
				return this;
			}

			/**
			 * <code>repeated .utils.TargetImage targets = 1;</code>
			 */
			public Builder removeTargets(int index) {
				if (targetsBuilder_ == null) {
					ensureTargetsIsMutable();
					targets_.remove(index);
					onChanged();
				} else {
					targetsBuilder_.remove(index);
				}
				return this;
			}

			/**
			 * <code>repeated .utils.TargetImage targets = 1;</code>
			 */
			public com.utils.Data.TargetImage.Builder getTargetsBuilder(int index) {
				return getTargetsFieldBuilder().getBuilder(index);
			}

			/**
			 * <code>repeated .utils.TargetImage targets = 1;</code>
			 */
			public com.utils.Data.TargetImageOrBuilder getTargetsOrBuilder(int index) {
				if (targetsBuilder_ == null) {
					return targets_.get(index);
				} else {
					return targetsBuilder_.getMessageOrBuilder(index);
				}
			}

			/**
			 * <code>repeated .utils.TargetImage targets = 1;</code>
			 */
			public java.util.List<? extends com.utils.Data.TargetImageOrBuilder> getTargetsOrBuilderList() {
				if (targetsBuilder_ != null) {
					return targetsBuilder_.getMessageOrBuilderList();
				} else {
					return java.util.Collections.unmodifiableList(targets_);
				}
			}

			/**
			 * <code>repeated .utils.TargetImage targets = 1;</code>
			 */
			public com.utils.Data.TargetImage.Builder addTargetsBuilder() {
				return getTargetsFieldBuilder().addBuilder(com.utils.Data.TargetImage.getDefaultInstance());
			}

			/**
			 * <code>repeated .utils.TargetImage targets = 1;</code>
			 */
			public com.utils.Data.TargetImage.Builder addTargetsBuilder(int index) {
				return getTargetsFieldBuilder().addBuilder(index, com.utils.Data.TargetImage.getDefaultInstance());
			}

			/**
			 * <code>repeated .utils.TargetImage targets = 1;</code>
			 */
			public java.util.List<com.utils.Data.TargetImage.Builder> getTargetsBuilderList() {
				return getTargetsFieldBuilder().getBuilderList();
			}

			private com.google.protobuf.RepeatedFieldBuilder<com.utils.Data.TargetImage, com.utils.Data.TargetImage.Builder, com.utils.Data.TargetImageOrBuilder> getTargetsFieldBuilder() {
				if (targetsBuilder_ == null) {
					targetsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<com.utils.Data.TargetImage, com.utils.Data.TargetImage.Builder, com.utils.Data.TargetImageOrBuilder>(
							targets_, ((bitField0_ & 0x00000001) == 0x00000001), getParentForChildren(), isClean());
					targets_ = null;
				}
				return targetsBuilder_;
			}

			// required int32 dataSize = 2;
			private int dataSize_;

			/**
			 * <code>required int32 dataSize = 2;</code>
			 */
			public boolean hasDataSize() {
				return ((bitField0_ & 0x00000002) == 0x00000002);
			}

			/**
			 * <code>required int32 dataSize = 2;</code>
			 */
			public int getDataSize() {
				return dataSize_;
			}

			/**
			 * <code>required int32 dataSize = 2;</code>
			 */
			public Builder setDataSize(int value) {
				bitField0_ |= 0x00000002;
				dataSize_ = value;
				onChanged();
				return this;
			}

			/**
			 * <code>required int32 dataSize = 2;</code>
			 */
			public Builder clearDataSize() {
				bitField0_ = (bitField0_ & ~0x00000002);
				dataSize_ = 0;
				onChanged();
				return this;
			}

			// required int32 size = 3;
			private int size_;

			/**
			 * <code>required int32 size = 3;</code>
			 */
			public boolean hasSize() {
				return ((bitField0_ & 0x00000004) == 0x00000004);
			}

			/**
			 * <code>required int32 size = 3;</code>
			 */
			public int getSize() {
				return size_;
			}

			/**
			 * <code>required int32 size = 3;</code>
			 */
			public Builder setSize(int value) {
				bitField0_ |= 0x00000004;
				size_ = value;
				onChanged();
				return this;
			}

			/**
			 * <code>required int32 size = 3;</code>
			 */
			public Builder clearSize() {
				bitField0_ = (bitField0_ & ~0x00000004);
				size_ = 0;
				onChanged();
				return this;
			}

			// @@protoc_insertion_point(builder_scope:utils.VectorTargetImages)
		}

		static {
			defaultInstance = new VectorTargetImages(true);
			defaultInstance.initFields();
		}

		// @@protoc_insertion_point(class_scope:utils.VectorTargetImages)
	}

	private static com.google.protobuf.Descriptors.Descriptor internal_static_utils_TargetImage_descriptor;
	private static com.google.protobuf.GeneratedMessage.FieldAccessorTable internal_static_utils_TargetImage_fieldAccessorTable;
	private static com.google.protobuf.Descriptors.Descriptor internal_static_utils_VectorTargetImages_descriptor;
	private static com.google.protobuf.GeneratedMessage.FieldAccessorTable internal_static_utils_VectorTargetImages_fieldAccessorTable;

	public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
		return descriptor;
	}

	private static com.google.protobuf.Descriptors.FileDescriptor descriptor;
	static {
		java.lang.String[] descriptorData = { "\n\010newproto\022\005utils\"\215\001\n\013TargetImage\022\014\n\004key"
				+ "s\030\001 \003(\002\022\013\n\003des\030\002 \003(\005\022\n\n\002id\030\003 \002(\005\022\r\n\005widt"
				+ "h\030\004 \002(\005\022\016\n\006height\030\005 \002(\005\022\014\n\004rows\030\006 \002(\005\022\014\n"
				+ "\004cols\030\007 \002(\005\022\014\n\004type\030\010 \002(\005\022\016\n\006keyNum\030\t \002("
				+ "\005\"Y\n\022VectorTargetImages\022#\n\007targets\030\001 \003(\013"
				+ "2\022.utils.TargetImage\022\020\n\010dataSize\030\002 \002(\005\022\014"
				+ "\n\004size\030\003 \002(\005B\021\n\tcom.utilsB\004Data" };
		com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner = new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
			public com.google.protobuf.ExtensionRegistry assignDescriptors(com.google.protobuf.Descriptors.FileDescriptor root) {
				descriptor = root;
				internal_static_utils_TargetImage_descriptor = getDescriptor().getMessageTypes().get(0);
				internal_static_utils_TargetImage_fieldAccessorTable = new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
						internal_static_utils_TargetImage_descriptor, new java.lang.String[] { "Keys", "Des", "Id", "Width", "Height", "Rows",
								"Cols", "Type", "KeyNum", });
				internal_static_utils_VectorTargetImages_descriptor = getDescriptor().getMessageTypes().get(1);
				internal_static_utils_VectorTargetImages_fieldAccessorTable = new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
						internal_static_utils_VectorTargetImages_descriptor, new java.lang.String[] { "Targets", "DataSize", "Size", });
				return null;
			}
		};
		com.google.protobuf.Descriptors.FileDescriptor.internalBuildGeneratedFileFrom(descriptorData,
				new com.google.protobuf.Descriptors.FileDescriptor[] {}, assigner);
	}

	// @@protoc_insertion_point(outer_class_scope)
}
